<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "in2contact"
 *
 * Auto generated by Extension Builder 2017-03-17
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'In2contact',
    'description' => 'Personendatenbank für Universitäten und Hochschulen',
    'category' => 'plugin',
    'author' => 'Alex Kellner',
    'author_email' => 'alexander.kellner@in2code.de',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.2.3',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.99.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
